create role anon; create role authenticated;
create schema auth; create schema storage;
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create function storage.foldername(name text) returns text[] language sql immutable as $$ select string_to_array(name,'/') $$;
grant usage on schema auth,storage to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;
create table companies(id uuid primary key default gen_random_uuid(),name text not null);
create table users(id uuid primary key,company_id uuid references companies,role text not null,status text default 'active');
create table client_users(id uuid default gen_random_uuid(),user_id uuid,company_id uuid,client_id uuid,role text,status text default 'active');
create table roles(id uuid primary key default gen_random_uuid());
create table user_roles(id uuid default gen_random_uuid(),user_id uuid,company_id uuid,role_id uuid);
create table role_permissions(role_id uuid,company_id uuid,permission_key text,level text);
create table sites(id uuid primary key default gen_random_uuid(),company_id uuid,client_id uuid,site_name text);
create table guards(id uuid primary key default gen_random_uuid(),user_id uuid,company_id uuid);
create table shifts(id uuid primary key default gen_random_uuid(),company_id uuid,site_id uuid,guard_id uuid,start_time timestamptz,end_time timestamptz,status text,shift_type text,notes text);
create table service_requests(id uuid primary key default gen_random_uuid(),company_id uuid not null,client_id uuid not null,site_id uuid,requester_id uuid not null,request_type text,priority text,description text,status text default 'submitted',internal_notes text,assigned_to uuid,resolution text,closed_at timestamptz,created_at timestamptz default now(),updated_at timestamptz default now());
create table client_invoices(id uuid primary key default gen_random_uuid(),company_id uuid not null,client_id uuid not null,billing_run_id uuid,status text);
create table client_invoice_disputes(id uuid primary key default gen_random_uuid(),company_id uuid not null,client_id uuid not null,invoice_id uuid not null,reason text not null,submitted_by uuid not null,status text default 'open',internal_notes text,client_visible_response text,created_at timestamptz default now());
create table billing_run_lines(id uuid primary key default gen_random_uuid(),company_id uuid,client_id uuid,billing_run_id uuid);
create table payment_allocations(id uuid primary key default gen_random_uuid(),company_id uuid,invoice_id uuid);
create table client_payments(id uuid primary key default gen_random_uuid(),company_id uuid,client_id uuid);
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text,owner_id text);
alter table service_requests enable row level security;
alter table client_invoices enable row level security;
alter table client_invoice_disputes enable row level security;
alter table billing_run_lines enable row level security;
alter table payment_allocations enable row level security;
alter table client_payments enable row level security;
alter table storage.objects enable row level security;
grant select,insert,update on service_requests to authenticated;
grant select,insert,update,delete on client_invoice_disputes to authenticated;
grant select,insert,delete on storage.objects to authenticated;

grant select on public.shifts,public.guards to authenticated;
